### ISSUE TITLE
Flex box에서 BootStrap의 Progress Bar를 사용하는 경우, 화면에 표시가 되지 않는 에러

### ISSUE THREAD

**Issue by younyikim** [younyikim/Quiz-App#2]
BootStrap의 Progress Bar를 사용하는 경우, 크기와 관련된 attribute들은 모두 Dynamic하게 잘 변화하지만화면에는 Progress Bar 가 표시되지 않는 상황이 있었다. 

index.html에 동일한 코드를 넣었을 때는 Progress bar가 정상적으로 보여지는데 반해,
quiz를 푸는 화면에서는 보여지지 않았다.

문제는 Progress Bar를 표시하려는 곳이, 
`div.quiz-progress` 내부였고, flex box를 사용했다.

  https://stackoverflow.com/questions/50921383/progress-bar-is-not-showing-at-all
위를 참고하여  문제를 해결하였다.

[bootstarp docs](https://getbootstrap.com/docs/4.1/layout/grid/)을 참고하면, 

> _In a grid layout, content must be placed within columns and only columns may be immediate children of rows.

'그리드 레이아웃을 사용할 때는 반드시 콘텐츠는 열 내에 배치되어야하며,  열만 행의 직계 자식 일 수 있습니다.' 라고 한다. 

[해결]
flex도 동일하게 적용될 것이라고 생각하여, Progress Bar를 row와 col로 감싸주어 문제를 해결했다.
```javascript
 <div class="quiz-progress">
            <div class="row" style="width: 80%;">
                <div class="col">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped bg-info" id="progress-bar" role="progressbar"
                            style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"> 
                        </div>
                    </div>
                    <p id="questionCnt"></p>
               </div>
          </div>
    </div>
```

```css
.quiz-progress{
    display: flex;
    flex-wrap: center;
    align-items: center;
    justify-content: center;
    grid-column: 1 / 4;
    grid-row : 3 / 4;
    height: 10vh;
}

```
